/**
 * Auto-generated by `anchor build` from programs/mercosuria/src/lib.rs
 * Place the real file at src/lib/mercosuria_idl.json after running:
 *   anchor build
 *   cp target/idl/mercosuria.json src/lib/mercosuria_idl.json
 *   cp target/types/mercosuria.ts src/lib/mercosuria_types.ts
 *
 * This file is a hand-crafted IDL that matches the Anchor program exactly.
 */

export const MERCOSURIA_IDL = {
  address: "MERCzKpGn4jqf9eFZSPVKMeS7WGmP4QhEGGdNLVwx1U",
  metadata: { name: "mercosuria", version: "0.1.0", spec: "0.1.0" },
  instructions: [
    {
      name: "initializePlatform",
      accounts: [
        { name: "platform", writable: true, signer: false },
        { name: "treasury", writable: false, signer: false },
        { name: "authority", writable: true, signer: true },
        { name: "systemProgram", address: "11111111111111111111111111111111" },
      ],
      args: [{ name: "feeBps", type: "u64" }],
    },
    {
      name: "registerLawyer",
      accounts: [
        { name: "lawyerProfile", writable: true, signer: false },
        { name: "lawyerVault", writable: false, signer: false },
        { name: "lawyer", writable: true, signer: true },
        { name: "systemProgram", address: "11111111111111111111111111111111" },
      ],
      args: [
        { name: "name", type: "string" },
        { name: "barNumber", type: "string" },
        { name: "jurisdiction", type: "string" },
        { name: "specialization", type: "string" },
        { name: "hourlyRateLamports", type: "u64" },
      ],
    },
    {
      name: "updateLawyerProfile",
      accounts: [
        { name: "lawyerProfile", writable: true, signer: false },
        { name: "lawyer", writable: false, signer: true },
      ],
      args: [
        { name: "hourlyRateLamports", type: { option: "u64" } },
        { name: "isActive", type: { option: "bool" } },
      ],
    },
    {
      name: "openCase",
      accounts: [
        { name: "platform", writable: true, signer: false },
        { name: "legalCase", writable: true, signer: false },
        { name: "caseEscrow", writable: true, signer: false },
        { name: "client", writable: true, signer: true },
        { name: "systemProgram", address: "11111111111111111111111111111111" },
      ],
      args: [
        { name: "title", type: "string" },
        { name: "description", type: "string" },
        { name: "caseType", type: { defined: { name: "CaseType" } } },
        { name: "budgetLamports", type: "u64" },
        { name: "deadlineTs", type: "i64" },
      ],
    },
    {
      name: "applyToCase",
      accounts: [
        { name: "legalCase", writable: true, signer: false },
        { name: "caseApplication", writable: true, signer: false },
        { name: "lawyerProfile", writable: false, signer: false },
        { name: "lawyer", writable: true, signer: true },
        { name: "systemProgram", address: "11111111111111111111111111111111" },
      ],
      args: [
        { name: "proposal", type: "string" },
        { name: "proposedFeeLamports", type: "u64" },
      ],
    },
    {
      name: "acceptLawyer",
      accounts: [
        { name: "legalCase", writable: true, signer: false },
        { name: "caseApplication", writable: true, signer: false },
        { name: "lawyer", writable: false, signer: false },
        { name: "client", writable: false, signer: true },
      ],
      args: [],
    },
    {
      name: "attachDocument",
      accounts: [
        { name: "legalCase", writable: true, signer: false },
        { name: "documentRecord", writable: true, signer: false },
        { name: "signer", writable: true, signer: true },
        { name: "systemProgram", address: "11111111111111111111111111111111" },
      ],
      args: [
        { name: "docHash", type: "string" },
        { name: "docTitle", type: "string" },
        { name: "docType", type: { defined: { name: "DocumentType" } } },
      ],
    },
    {
      name: "releasePayment",
      accounts: [
        { name: "platform", writable: false, signer: false },
        { name: "legalCase", writable: true, signer: false },
        { name: "caseEscrow", writable: true, signer: false },
        { name: "lawyerProfile", writable: true, signer: false },
        { name: "lawyerWallet", writable: true, signer: false },
        { name: "treasury", writable: true, signer: false },
        { name: "client", writable: false, signer: true },
      ],
      args: [{ name: "amountLamports", type: "u64" }],
    },
    {
      name: "closeCase",
      accounts: [
        { name: "platform", writable: true, signer: false },
        { name: "legalCase", writable: true, signer: false },
        { name: "caseEscrow", writable: true, signer: false },
        { name: "lawyerProfile", writable: true, signer: false },
        { name: "client", writable: true, signer: true },
      ],
      args: [
        { name: "outcome", type: { defined: { name: "CaseOutcome" } } },
        { name: "resolutionNotes", type: "string" },
      ],
    },
    {
      name: "submitReview",
      accounts: [
        { name: "legalCase", writable: false, signer: false },
        { name: "lawyerReview", writable: true, signer: false },
        { name: "lawyerProfile", writable: true, signer: false },
        { name: "lawyer", writable: false, signer: false },
        { name: "client", writable: true, signer: true },
        { name: "systemProgram", address: "11111111111111111111111111111111" },
      ],
      args: [
        { name: "rating", type: "u8" },
        { name: "comment", type: "string" },
      ],
    },
    {
      name: "raiseDispute",
      accounts: [
        { name: "legalCase", writable: true, signer: false },
        { name: "dispute", writable: true, signer: false },
        { name: "signer", writable: true, signer: true },
        { name: "systemProgram", address: "11111111111111111111111111111111" },
      ],
      args: [{ name: "reason", type: "string" }],
    },
    {
      name: "resolveDispute",
      accounts: [
        { name: "platform", writable: false, signer: false },
        { name: "legalCase", writable: true, signer: false },
        { name: "dispute", writable: true, signer: false },
        { name: "caseEscrow", writable: true, signer: false },
        { name: "lawyerProfile", writable: true, signer: false },
        { name: "client", writable: true, signer: false },
        { name: "lawyerWallet", writable: true, signer: false },
        { name: "treasury", writable: true, signer: false },
        { name: "authority", writable: false, signer: true },
      ],
      args: [
        { name: "ruling", type: { defined: { name: "DisputeRuling" } } },
        { name: "notes", type: "string" },
      ],
    },
  ],
  accounts: [
    { name: "PlatformState", discriminator: [0, 0, 0, 0, 0, 0, 0, 1] },
    { name: "LawyerProfile", discriminator: [0, 0, 0, 0, 0, 0, 0, 2] },
    { name: "LegalCase", discriminator: [0, 0, 0, 0, 0, 0, 0, 3] },
    { name: "CaseApplication", discriminator: [0, 0, 0, 0, 0, 0, 0, 4] },
    { name: "DocumentRecord", discriminator: [0, 0, 0, 0, 0, 0, 0, 5] },
    { name: "LawyerReview", discriminator: [0, 0, 0, 0, 0, 0, 0, 6] },
    { name: "Dispute", discriminator: [0, 0, 0, 0, 0, 0, 0, 7] },
  ],
  types: [
    {
      name: "CaseType",
      type: {
        kind: "enum",
        variants: [
          { name: "ContractDispute" },
          { name: "IntellectualProperty" },
          { name: "CommercialLaw" },
          { name: "LaborLaw" },
          { name: "ConsumerProtection" },
          { name: "RegulatoryCompliance" },
          { name: "ArbitrationMercosur" },
          { name: "TradeLaw" },
          { name: "Other" },
        ],
      },
    },
    {
      name: "CaseStatus",
      type: {
        kind: "enum",
        variants: [
          { name: "Open" },
          { name: "InProgress" },
          { name: "Disputed" },
          { name: "Closed" },
        ],
      },
    },
    {
      name: "CaseOutcome",
      type: {
        kind: "enum",
        variants: [
          { name: "ClientWon" },
          { name: "ClientLost" },
          { name: "SettledAmicably" },
          { name: "Dismissed" },
        ],
      },
    },
    {
      name: "DocumentType",
      type: {
        kind: "enum",
        variants: [
          { name: "Contract" },
          { name: "Evidence" },
          { name: "LegalBrief" },
          { name: "CourtOrder" },
          { name: "Settlement" },
          { name: "InvoiceReceipt" },
          { name: "IdentityDocument" },
          { name: "Other" },
        ],
      },
    },
    {
      name: "DisputeRuling",
      type: {
        kind: "enum",
        variants: [
          { name: "FavorClient" },
          { name: "FavorLawyer" },
          { name: "SplitEvenly" },
        ],
      },
    },
  ],
  events: [
    { name: "CaseOpened", fields: [] },
    { name: "LawyerRegistered", fields: [] },
    { name: "PaymentReleased", fields: [] },
    { name: "CaseClosed", fields: [] },
    { name: "DisputeRaised", fields: [] },
    { name: "DisputeResolved", fields: [] },
    { name: "ReviewSubmitted", fields: [] },
    { name: "DocumentAttached", fields: [] },
  ],
  errors: [
    { code: 6000, name: "FeeTooHigh", msg: "Fee basis points too high (max 1000 = 10%)" },
    { code: 6001, name: "StringTooLong", msg: "String exceeds maximum length" },
    { code: 6002, name: "InvalidAmount", msg: "Amount must be greater than zero" },
    { code: 6003, name: "InsufficientStake", msg: "Insufficient stake — must stake at least 1 SOL" },
    { code: 6004, name: "CaseNotOpen", msg: "Case is not open for applications" },
    { code: 6005, name: "FeeExceedsBudget", msg: "Proposed fee exceeds case budget" },
    { code: 6006, name: "LawyerNotActive", msg: "Lawyer profile is not active" },
    { code: 6007, name: "Unauthorized", msg: "Unauthorized" },
    { code: 6008, name: "CaseNotInProgress", msg: "Case is not currently in progress" },
    { code: 6009, name: "InsufficientEscrow", msg: "Insufficient funds in escrow" },
    { code: 6010, name: "CaseAlreadyClosed", msg: "Case has already been closed" },
    { code: 6011, name: "CaseNotClosed", msg: "Case is not closed" },
    { code: 6012, name: "NotDisputed", msg: "Case is not under dispute" },
    { code: 6013, name: "InvalidRating", msg: "Rating must be between 1 and 5" },
    { code: 6014, name: "InvalidDeadline", msg: "Deadline must be in the future" },
    { code: 6015, name: "TooManyDocuments", msg: "Maximum number of documents reached" },
  ],
} as const;

export type MercosuriaIDL = typeof MERCOSURIA_IDL;
